### PR TITLE
Chore: Add semantic highlighting to bash variables and commands

### PR DESCRIPTION
**Pull request by idillon-sfl**
In the following example, it adds highlighting to the command `do_stuff` and the variable `$FOO`, which were not handled before.

Screenshot from 2024-06-07 03-16-01

### CODE REVIEW

**Comment by deribaucourt** [comment]
In `$FOO`, the `$` sign should also be highlighted in blue

**Review by WilsonZiweiWang — APPROVED** [review]
LGTM

**Comment by idillon-sfl** [comment]
> In `$FOO`, the `$` sign should also be highlighted in blue

I found the default highlighting of Shell code in VS Code quite inconsistent for variables. Here's an example in a shell file:
Screenshot from 2024-06-12 14-16-54


For `$FOO` and `"$FOO"`, the dollar sign has the same color as the variable name. However, for `"${FOO}"` it has the color of string, and for `${FOO}` it still has different colors. Maybe all of this has some meaning, but I failed to find any sense out of it.

In comparison, here's what we have with this PR:
Screenshot from 2024-06-12 14-16-05

So I've been thinking of various approaches:
1. We consider the current behavior just as good (or bad?) as the default handling of Shell code and keep it as is.  
2. We consider the behavior in shell files makes sense and we try to do the exact same thing.  
3. We have both `$` and `${` the same color as the variable name.  
4. We have both `$` and `${` the same color, but distinct to the variable name.  
5. We have `$` the same color as the variable name, but `${` with a color distinct to the variable name.

**Comment by deribaucourt** [comment]
> 1. rent behavior just as good (or bad?) as the default handling of Shell code and keep it as is.

We could report this slight misbehavior in the appropriate repository, this looks like an external issue.

**Review by deribaucourt — APPROVED** [review]

**Comment by idillon-sfl** [comment]
I suggest we keep it in mind and handle `$` and `${` in a separate PR, both the same color, maybe as operators.

**Pull request merged**
