### PR TITLE
Make language server able to run standalone (for CoC.nvim) 

### LINKED ISSUE #22: How to integrate this into COC.nvim?
The COC LSP plugin for Vim should in theory be able to use this. Here is a link

https://github.com/neoclide/coc.nvim/wiki/Language-servers#register-custom-language-servers

I have compiled the server and tried the following configuration

```json
"bitbake": {
      "module": "~/Downloads/vscode-bitbake/client/server/server.js",
      "args": [
        "--stdio"
      ],
	  "settings": {
		  "bitbake.pathToBuildFolder": "~/Workspace/Yocto/build",
		  "bitbake.pathToBitbakeFolder": "~/Workspace/Yocto/bitbake",
		  "bitbake.pathToEnvScript": "~/Workspace/Yocto/openembedded-core/oe-init-build-env",
	  },
      "filetypes": [
        "bitbake"
      ]
	}
```

It doesn't respond though, although it should if it uses VSCode's LSP protocol. Can you give any hints on how to get this to work?

### PR DESCRIPTION
**Pull request by deribaucourt**
Fixes #22

### CODE REVIEW

**Comment by deribaucourt** [comment]
@Freed-Wu This is just a draft for now, but it should be compatible with VIM and VSCode now.
I'd like to improve the documentation and do other minor fixes before merging it.

**Comment by Freed-Wu** [comment]
OK, I'll close #156 and #167.

**Review by WilsonZiweiWang — APPROVED** [review]
Looks awesome!

**Comment by jclsn** [comment]
Awesome!

**Pull request merged**
