### PR TITLE
Fix URL errors when running on Windows

### PR DESCRIPTION
**Pull request by WilsonZiweiWang**
Ticket No. 13878

### CODE REVIEW

**Review by deribaucourt — DISMISSED** [review]
Does this fix the crash in #42?
Do other errors happen?
Once we have something compatible with windows, we also need to add the target in the npm run package script

**Comment by deribaucourt** [comment]
Closes #42

**Review by deribaucourt — APPROVED** [review]
my tests on windows with this PR:
 - No language server crash (definitions, hover work)
 - Embedded languages are not working due to URI handling on Windows
 - Running bitbake gives errors that can be disabled through "Don't show again"
 - SSH session to a Linux machine provides a Linux native experience
 - didn't test WSL

Added a commit for publishing

**Review by idillon-sfl — APPROVED** [review]
I see. GitHub actually *requires* me to approve this PR.

I could not test this change, since I do not have access to Windows. Looks fine to me, however.

**Pull request merged**
