### PR TITLE
Add Rename feature

### PR DESCRIPTION
**Pull request by WilsonZiweiWang**
Ticket: 14641

### CODE REVIEW

**Review by idillon-sfl — COMMENTED** [review]
That's nice, however it does not handle Python variables.

Example:
```
FOO = ""
python () {
  d.getVar("FOO")
}
```

Both `FOO` refer to the same variable, and should be renamed together.

I think it could be done easily (sorry if I'm wrong) with a function similar to `getVariableExpansionSymbols` and `getGlobalDeclarationSymbols`, but based on `isPythonDatastoreVariable`

**Comment by WilsonZiweiWang** [comment]
> Both `FOO` refer to the same variable, and should be renamed together.
> 
> I think it could be done easily (sorry if I'm wrong) with a function similar to `getVariableExpansionSymbols` and `getGlobalDeclarationSymbols`, but based on `isPythonDatastoreVariable`

`isPythonDatastoreVariable`  can be used when triggering the rename, but we still need the info about the range to apply the edit, which this function can't provide. We can store the info (including the range) about variables that appear in the Python data store functions as we did with global declarations and variable expansion symbols. The rest will be similar, which is get the stored symbols range and generate edits.

**Comment by idillon-sfl** [comment]
> > Both `FOO` refer to the same variable, and should be renamed together.
> > I think it could be done easily (sorry if I'm wrong) with a function similar to `getVariableExpansionSymbols` and `getGlobalDeclarationSymbols`, but based on `isPythonDatastoreVariable`
> 
> `isPythonDatastoreVariable` can be used when triggering the rename, but we still need the info about the range to apply the edit, which this function can't provide. We can store the info (including the range) about variables that appear in the Python data store functions as we did with global declarations and variable expansion symbols. The rest will be similar, which is get the stored symbols range and generate edits.

Yes, this is what i meant to say 👍

**Comment by idillon-sfl** [comment]
I take the liberty to merge myself, in order to avoid a bunch of conflicts with the changes I am currently working on.

**Pull request merged**
