### PR TITLE
Feat: Add completion and hover for variable expansion inside bash regions

### PR DESCRIPTION
**Pull request by idillon-sfl**
Screenshot from 2024-03-08 16-22-04
Screenshot from 2024-03-08 16-22-26

### CODE REVIEW

**Review by deribaucourt — COMMENTED** [review]
LGTM however I get diagnostics where symbols where detected as defined inside Bash regions.
Also, completion/hover doesn't activate if the variable is not inside curly braces. Ex: `$WORKDIR` instead of `${WORKDIR}` 
image

**Comment by idillon-sfl** [comment]
The previous version of tree-sitter-bitbake would break in many places because of bad handling of braces in bash regions. It would produce incomplete "embedded language documents", which may explain why you see diagnostics you would not see before.

The diagnostic showed on the screenshot looks to me like expected shellcheck's default behavior. What do you think?

Variables such as `$WORKDIR` is not into the current scope of the PR. It would require further changes in tree-sitter-bitbake.

**Comment by idillon-sfl** [comment]
This PR updates the version of tree-sitter-bitbake. Before this PR, the whole `do_prepare_config` function would not get parsed and would not reach the "embedded language document". In staging, the "embedded language document" is filled by white spaces, and this is why Shellcheck does not give warnings. In this PR, we can see the function.

I don't see how "Double quote to prevent globbing word and word splitting" is a false positive. Indeed, the variable is not surrounded by double quote. If the user does not like this warning, it can excluded in Shellcheck's settings

For the undefined variables such as `DO_IPv4`, [this PR](https://github.com/yoctoproject/vscode-bitbake/pull/153) might help (I've not checked), but there's probably some amelioration  we still can bring to the undefined variables detection.

**Comment by idillon-sfl** [comment]
the new push is just rebasing, since there was a conflict on tree-sitter-bitbake.wasm

**Comment by idillon-sfl** [comment]
`DO_IPv4` does not appear as undefined [after the scan on this PR](https://github.com/yoctoproject/vscode-bitbake/pull/153) with the new tree-sitter-bitbake's version introduced here

**Comment by WilsonZiweiWang** [comment]
> `DO_IPv4` does not appear as undefined [after the scan on this PR](https://github.com/yoctoproject/vscode-bitbake/pull/153) with the new tree-sitter-bitbake's version introduced here

I think we can push our custom patches to your `tree-sitter-bitbake` repo from now on.

**Review by deribaucourt — APPROVED** [review]

**Pull request merged**
