### PR TITLE
UI: Synchronize node-pty terminal dimensions with VS Code terminal di…

### PR DESCRIPTION
**Pull request by deribaucourt**
…mensions

This makes the progress bars of bitbake fill the entire terminal width when the terminal is resized or opened, or reused.

### CODE REVIEW

**Comment by idillon-sfl** [comment]
After several attempts, I am really not sure what this is supposed to fix

Screenshot from 2024-02-22 11-28-14
Screenshot from 2024-02-22 11-47-44

**Comment by deribaucourt** [comment]
Very weird that you get this. It makes the progress bar rightly fit the terminal width for Paul and I.
I'd like to know what difference is causing this on your setup.
What shell are you using? With shell plugins that might be sensitive to terminal width?
Do you have modified VSCode settings linked to the terminal?
Is your computer expecting \r\n instead of  \n in some way?
What version of VSCode are you running?

Here's what it should look like when running bitbake commands:
The progress bar fits terminal when it's small
image
The progress bar fits terminal when it's big
image

**Comment by idillon-sfl** [comment]
I use VS Code 1.86.2. 

I don't have any extension related to the terminals, and I don't remember having set any setting related to it.

I've not managed to reproduce the first screenshot in the `BitBake: Scan Project` terminal. I still see it in the `Debug Console`. It seems to happen when I redimension the terminal while the loading is going on.

Screenshot from 2024-02-23 10-05-12
Screenshot from 2024-02-23 10-30-28

I am on Ubuntu, I don't see any reason my terminals would expect `\r\n`.

**Comment by deribaucourt** [comment]
It's pretty much expected in the debug terminal, it doesn't handle erasing lines so we can't do much about it. Only thing would be moving bitbake outputs into a "verbose" category?
I can't figure out what's hapening on the terminal screenshot on your end though..

**Review by idillon-sfl — APPROVED** [review]
I'm thinking it is not worth spending too much time trying to understand what is wrong with my config. If it works for some people, then it is good enough.

**Pull request merged**
