### PR TITLE
Fix: Remove definition inherit integration test

### PR DESCRIPTION
**Pull request by deribaucourt**
We already have a unit test for this in
server/src/__tests__/definition.test.ts

This test randomly got stuck in CI.

### CODE REVIEW

**Comment by deribaucourt** [comment]
Let's run this at least 10 times in CI to validate 
image

**Comment by idillon-sfl** [comment]
I'm thinking this integration test is useful to ensure middlewareDefinition is handling onCompletion properly. The way that middleware handles its "next" is more complex than for the other middlewares. Maybe I should spend some time trying to debug it.

**Comment by deribaucourt** [comment]
I'm going to keep running the CI 10 times. That way we'll have the certainty it's that specific test

**Comment by deribaucourt** [comment]
10 CI have passed 
image

**Comment by deribaucourt** [comment]
Merging this at least temporarily @idillon-sfl feel free to investigate and fix this test :)

**Comment by deribaucourt** [comment]
Well it's not the only integration test randomly failing. We got the syntax error one to fail in https://github.com/yoctoproject/vscode-bitbake/actions/runs/8230442561/job/22503664830

**Comment by WilsonZiweiWang** [comment]
> Well it's not the only integration test randomly failing. We got the syntax error one to fail in https://github.com/yoctoproject/vscode-bitbake/actions/runs/8230442561/job/22503664830

This was the issue that kept failing the CI before the timeout one. I haven't seen this for a while.

**Comment by WilsonZiweiWang** [comment]
I think it would be Better to comment it out instead of deleting it. It's easier in case we want to bring it back sometime in the future

**Review by WilsonZiweiWang — APPROVED** [review]

**Comment by deribaucourt** [comment]
> I think it would be Better to comment it out instead of deleting it. It's easier in case we want to bring it back sometime in the future

I find dead code to be a poor programming practice. If we want to restore that test, we simply have to `git revert` the commit. The alternative would be to add a TODO comment remininding us that a test existed here and could be reverted when we get more knowledge on integration tests. But I doubt we'll ever make progress on this in the near future

**Comment by WilsonZiweiWang** [comment]
> > I think it would be Better to comment it out instead of deleting it. It's easier in case we want to bring it back sometime in the future
> 
> 
> 
> I find dead code to be a poor programming practice. If we want to restore that test, we simply have to `git revert` the commit. The alternative would be to add a TODO comment remininding us that a test existed here and could be reverted when we get more knowledge on integration tests. But I doubt we'll ever make progress on this in the near future

A TODO will serve the same purpose. Because deleted code won't be remembered without reminders.

**Pull request merged**
